spring.application.name=Spring Boot Web Tutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/priyeshkumar/documents/MVC-project/Db
spring.datasource.username=PriyeshDB
spring.datasource.password=Priyesh123
spring.jpa.hibernate.ddl-auto=update
server.port=8081
